### ISSUE TITLE
Homepage category filters. Seeing some problems on mobile and desktop

### ISSUE THREAD

**Issue by andypbrowne** [karlabrowne/karlakratzpoetry#45]
https://user-images.githubusercontent.com/7572176/146648393-ae5327ca-733f-4f61-ae83-8395c9df9b58.mov

Can we make the category filter pills on the homepage route directly to the correct filtered view just as the functionality works from /poems?

**Comment by d4rekanguok** [comment]
Nice catch, thanks Andy! I've addressed this in #46, please have a look
